# Просто релиз без всего по тэгу
name: Create Release

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: version x.y.z
        required: true
        type: string


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Changes
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CHANGE.md
          sparse-checkout-cone-mode: false

      - name: Generate Changelog
        run: |
          cat CHANGE.md > CHANGE.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGE.txt
